endpoints:
  cep:
    base-url: http://localhost:8089/cep

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;"
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2.console.enabled: true
  flyway:
    clean-disabled: false
    locations: classpath:db/migration/test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
  main:
    lazy-initialization: false
