endpoints:
  cep:
    base-url: http://localhost:8089/cep

feign:
  #The next attributes are handled manually, as there is a bug when setting timeouts and disabling follow redirects
  connectTimeout: 5000
  readTimeout: 5000
  followRedirects: false
  ignore-ssl: false
  #end
  client.config.default:
    default:
      loggerLevel: BASIC
      retryer: dev.sandrocaseiro.springbootitExample.clients.retryers.NoRetryer
  compression:
    request.enabled: true
    response.enabled: true
  okhttp.enabled: true

locale:
  default: en-US

logging:
  level:
    root: INFO

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  application:
    name: springbootitExample
  datasource:
#    url: "jdbc:h2:mem:testdb;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS TEMPLATE\\;SET SCHEMA_SEARCH_PATH TEMPLATE;"
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;"
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2.console.enabled: true
  http:
    encoding:
      charset: UTF-8
      force: true
  flyway:
    enabled: true
    clean-disabled: false
    locations: classpath:db/migration/common,classpath:db/migration/test
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
        proc:
          param_null_passing: true
          jdbc:
            lob:
              non_contextual_creation: true
            time_zone: UTC
  main:
    banner-mode: OFF
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: ALWAYS
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 6MB
